---
output:
  bookdown::pdf_document2:
    toc: false
    number_sections: false
documentclass: article
geometry: margin=1in
fontsize: 12pt
linestretch: 2
fig.cap: true
header-includes:
  - \usepackage{float}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(purrr)
library(ggplot2)
library(table1)
dat_raw <- read.csv(here::here("P1/DataRaw", "hiv_6624_final.csv"))
```

<!-- Title here: -->
# \textit{Analysis Plan for HAART Outcomes by Drug Use}

<!-- Name here: -->
Ezra Weible[^1]

[^1]: Biostatistics Masters Student, Colorado School of Public Health, CU Anschutz Medical Campus

## Introduction

This project uses data from the Multicenter AIDS Cohort Study, an ongoing prospective cohort that studies HIV-1 infection among homosexual and bisexual men in four major US cities. This report analyzed a subset of 463 MACS participants with viral load (log10 HIV copies/mL blood), CD4+ T cell count, and SF-36 aggregate physical and mental quality‑of‑life measured at baseline (pre‑HAART initiation) and two years after starting HAART. Baseline information on hard drug use, defined as injection drugs or illicit heroin/opiate use, was available along with and other relevant covariates including age, BMI, smoking status, education, and race/ethnicity. 

The primary question of interest was whether individuals who reported hard drug use at baseline experienced different treatment outcomes two years after starting HAART compared to those who did not after adjusting for baseline covariates. The outcomes were viral load (log10 HIV copies/mL blood), CD4+ T cell count, and SF-36 aggregate physical and mental quality‑of‑life. The covariates were age, BMI, smoking status, education, and race/ethnicity. The secondary analysis will descriptively assess whether the difference or lack of difference in treatment response between hard drug users and non hard drug users after adjusting for baseline covariates can be explained by year-2 HAART adherence. These two questions were both assessed from a frequentist and a Bayesian framework.

## Methods

All analyses were conducted in R v4.5.2 (2025-10-31 ucrt). BMI values coded as -1 or 999 and two implausible values over 250 were set to missing. Categorical covariates were collapsed as follows to ensure adequate sample sizes by category: smoking status (current vs former/non smoker), education status (no college degree vs college degree and above), race/ethnicity (white non-Hispanic vs other), and adherence (95% and above vs <95%). Viral load was converted to the log10 scale. Participants were removed if they were missing baseline  after removing any individuals with incomplete baseline viral load, CD4+ T cell count, physical and mental quality of life scores, age, BMI, smoking status, education, or race/ethnicity. Participants were also removed if they were missing year two outcomes or year two adherence. The final sample size was 463 individuals.

For each outcome at year 2, linear regression was used to identify the association with hard drug use at baseline, adjusting for age, BMI, smoking status, education, and race/ethnicity. Frequentist models reported point estimates, 95\% confidence intervals (CI), and unadjusted p-values. Bayesian models were implemented using STAN with vaguely informative priors as prior knowledge is limited: N(0,1000) for regression coefficients and half-normal(0,1000) for residual SD. The intercept was not centered due to the large variance and model fit was diagnosed with R-hat and ESS. Bayesian models reported posterior means, 95% highest posterior density intervals (HPDI), and posterior probabilities. Posterior probabilities were calculated from clinically meaningful differences for each outcome (two-sided), defined as follows: 0.5 log10 (viral load), 50 cells (CD4+ T cell count), and 2 points (quality of life). These models were additionally fit including year 2 adherence and descriptively compared to the original models. 

## Appendix

Code Directory: https://github.com/eweible/BIOS6624.git

File name: P1/Code/P1_Data_Analysis_Plan.Rmd

Data Directory: C:/Users/weiblee/OneDrive/Documents/Anschutz/Spring 2026/6624_Advanced/Weible_Advanced/P1/DataRaw
