---
title: "P3_Data_Exploration"
output: html_document
date: "2026-04-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(survival)
library(survminer)
library(here)
library(table1)
dat_raw <- read.csv(here::here("P3/DataRaw", "frmgham2.csv"))
```

```{r}
View(dat_raw)
```

Data cleaning
```{r}
dat_10 <- dat_raw %>%
  filter(!(STROKE == 1 & TIMESTRK == 0)) %>%
    # Remove baseline stroke
  mutate(
    time_yrs = TIMESTRK / 365.25,
    time_10 = pmin(time_yrs, 10),
    stroke_event = if_else(STROKE == 1 & time_yrs <= 10, 1, 0)
  ) # Adjust time vars
dat_10 <- dat_10 %>%
  select(
    RANDID, STROKE, SEX, time_10, stroke_event, AGE, DIABETES, SYSBP, PREVCHD, 
    BPMEDS, CURSMOKE, TOTCHOL, BMI
  ) # Restrict to needed vars
dat_10 <- dat_10 %>%
  mutate(
    SEX = factor(SEX, labels = c("Male", "Female")),
    DIABETES = factor(DIABETES, levels = c(0,1), labels = c("No","Yes")),
    CURSMOKE = factor(CURSMOKE, levels = c(0,1), labels = c("No","Yes")),
    PREVCHD = factor(PREVCHD, levels = c(0,1), labels = c("No","Yes")),
    BPMEDS = factor(BPMEDS, levels = c(0,1), labels = c("No","Yes"))
  ) # Convert to factors
dat_cc <- dat_10 %>%
  filter(!is.na(time_10), !is.na(stroke_event)) %>%
  filter(complete.cases(
    AGE, SYSBP, DIABETES, PREVCHD, BPMEDS, CURSMOKE, TOTCHOL, BMI
  )) # Complete case dataset for all vars
```

Kaplan-Meier curves and log-rank tests
```{r}
surv_object <- Surv(time = dat_cc$time_10, event = dat_cc$stroke_event)

## By sex
fit_sex <- survfit(surv_object ~ SEX, data = dat_cc)
ggsurvplot(fit_sex, data = dat_cc, ylim = c(0.90, 1.00),
           xlab = "Years", ylab = "Stroke-free survival")$plot
survdiff(surv_object ~ SEX, data = dat_cc)

## By diabetes
fit_diab <- survfit(surv_object ~ DIABETES, data = dat_cc)
ggsurvplot(fit_diab, data = dat_cc, ylim = c(0.90, 1.00),
           xlab = "Years", ylab = "Stroke-free survival")$plot
survdiff(surv_object ~ DIABETES, data = dat_cc)

## By high BP
dat_cc <- dat_cc %>%
  mutate(HIGHBP = if_else(SYSBP >= 160, 1, 0))
fit_bp <- survfit(Surv(time_10, stroke_event) ~ HIGHBP, data = dat_cc)
ggsurvplot(fit_bp, data = dat_cc, ylim = c(0.90, 1.00),
           xlab = "Years", ylab = "Stroke-free survival")$plot
survdiff(Surv(time_10, stroke_event) ~ HIGHBP, data = dat_cc)
```

Table 1:
```{r}
table1(~ AGE + SYSBP + DIABETES + PREVCHD + BPMEDS + CURSMOKE + TOTCHOL + BMI 
       | SEX, data = dat_cc)
```
