---
output:
  bookdown::pdf_document2:
    toc: false
    number_sections: false
documentclass: article
geometry: margin=1in
fontsize: 12pt
linestretch: 2
fig.cap: true
header-includes:
  - \usepackage{float}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Title here: -->
# \textit{Analysis Plan for HAART Outcomes by Drug Use}

<!-- Name here: -->
Ezra Weible[^1]

[^1]: Biostatistics Masters Student, Colorado School of Public Health, CU Anschutz Medical Campus

## Aim 1 Analysis Plan

#### Hypothesis 1a: 

- Outcome 1: Memory Consolidation (continuous)
  - 1 year
    - MST measure
- Outcome 2: Cortical Thickness (continuous)
  - 1 year
- Predictors:
  - Cytokines (continuous)
    - Baseline
      - TNF-alpha, IL-6 
  - Chemokines (continuous)
    - Baseline
      - MCP-1, Eotaxin-1
- Additional Covariates
  - Required: age, sex, baseline outcome
  - Plausible confounders: education, APOE, CDR at baseline, geriatric depression rating
  - Supplemental covariates with likely correlation (add only if AIC improves and be cautious in interpreting): BMI, hypercholesterolemia, blood pressure, NSAID, immune-related health conditiions, cardiovascular risk
- Alternative Hypothesis: for each outcome, $\beta_1 < 0$ 
  - Higher baseline inflammation leads to worse cognition or thickness at 1 year
  - Model with simple linear regression, with a separate model for each outcome.
    - General outline: $Outcome_{Y1} = \beta_0 + \beta_1 Marker_{Y0} + \beta_2 Outcome_{Y0} + \beta_n covariates + \epsilon$
    - Fit separate models for each cytokine/chemokine due to potential correlations, have the joint model be exploratory. 
    - Within this hypothesis, adjust with FDR
  
#### Hypothesis 1b: 

- Outcome 1: Episodic Memory Outcomes (continuous)
  - Change over 1 year
    - 20' Delay, Total Correct
    - Recognition, D-Prime
    - 15' Delay, Total Correct
    - Proportion Correct
    - 1-Week Delay, Total Correct
- Outcome 2: Cortical Thickness (continuous)
  - Change over 1 year
- Predictors:
  - Cytokines (continuous)
    - Change over 1 year
      - TNF-alpha, CPN1, Eotaxin-1 MCP-1
  - Chemokines (continuous)
    - Change over 1 year
      - MCP-1, Eotaxin-1
- Additional Covariates
  - Required: age, sex
  - Plausible confounders: education, APOE, CDR at baseline, geriatric depression rating
  - Supplemental covariates with likely correlation (add only if AIC improves and be cautious in interpreting): BMI, hypercholesterolemia, blood pressure, NSAID, immune-related health conditiions, cardiovascular risk
- Alternative Hypothesis: for each outcome, $\beta_1 < 0$ 
  - Greater increases in inflammatory markers leads to greater declines in cognition or thickness from baseline to 1 year.
  - Model with simple linear regression, with a separate model for each outcome.
    - General outline: $Outcome_{Y1-Y0} = \beta_0 + \beta_1 Marker_{Y1-Y0} + \beta_2 Outcome_{Y0} + \beta_n covariates + \epsilon$
      - Fit separate models for each cytokine/chemokine due to potential correlations, have the joint model be exploratory. 
    - Within this hypothesis, adjust with FDR

## Aim 2 Analysis Plan

#### Primary Hypothesis 

- Outcome 1: Episodic Memory Outcomes (continuous)
  - 1 year
    - 20' Delay, Total Correct
    - Recognition, D-Prime
    - 15' Delay, Total Correct
    - Proportion Correct
    - 1-Week Delay, Total Correct
- Outcome 2: Cortical Thickness (continuous)
  - 1 year
- Predictors:
  - Amyloid deposition (continuous)
    - Baseline
  - Cytokines (continuous)
    - Baseline
      - TNF-alpha, IL-6 
  - Chemokines (continuous)
    - Baseline
      - MCP-1, Eotaxin-1
- Same potential covariates as Aim 1
- Alternative Hypothesis: for each outcome, $\beta_3 < 0$ 
  - The effect of inflammatory markers on decline is stronger at higher amyloid levels.
  - Model with simple linear regression, with a separate model for each outcome.
    - General outline: $Outcome_{Y1} = \beta_0 + \beta_1 Amyloid_{Y0} + \beta_2 Marker_{Y0} + \beta_3 Amyloid_{Y0}*Marker_{Y0} + \beta_n covariates + \epsilon$
      - Fit separate models for each cytokine/chemokine due to potential correlations, have the joint model be exploratory. 
    - Within this hypothesis, adjust with FDR

      
#### Secondary Hypothesis

- Outcome 1: Episodic Memory Outcomes (continuous)
  - Change over 1 year (aka adjust for baseline value)
    - 20' Delay, Total Correct
    - Recognition, D-Prime
    - 15' Delay, Total Correct
    - Proportion Correct
    - 1-Week Delay, Total Correct
- Outcome 2: Cortical Thickness (continuous)
  - Change over 1 year (aka adjust for baseline value)
- Predictors:
  - Amyloid deposition (continuous)
    - Baseline
  - Cytokines (continuous)
    - Change over 1 year
      - TNF-alpha, IL-6 
  - Chemokines (continuous)
    - Change over 1 year
      - MCP-1, Eotaxin-1
- Same potential covariates as Aim 1
- Alternative Hypothesis: for each outcome, $\beta_3 < 0$ 
  - The effect of inflammatory markers on decline is stronger at higher amyloid levels.
  - Model with simple linear regression, with a separate model for each outcome.
    - General outline: $Outcome_{Y1-Y0} = \beta_0 + \beta_1 Amyloid_{Y0} + \beta_2 Marker_{Y1-Y0} + \beta_3 Amyloid_{Y0}*Marker_{Y1-Y0} + \beta_4 Outcome_{Y0} + \beta_n covariates + \epsilon$
      - Fit separate models for each cytokine/chemokine due to potential correlations, have the joint model be exploratory. 
    - Within this hypothesis, adjust with FDR


## Power Analysis Plan

- For Aim 1, for each hypothesis, simplify to a correlation test as the regression for each outcome has a continuous variable of interest. Calculate a power of 80\% and use the maximum sample size provided to get a potential difference that can be identified. Assuming that the additional covariates (e.g. age, sex) are precision variables, this may allow for us to have greater power in truth. 

4. What power/sample size calculations you will conduct for each of the hypotheses of interest

5. Not required for interim, but will be required for final: thoughts on your approach to type I error control.

Code Directory: https://github.com/eweible/BIOS6624.git

File name: P2/Code/P2_Data_Analysis_Plan.Rmd