---
output:
  bookdown::pdf_document2:
    toc: false
    number_sections: false
documentclass: article
geometry: margin=1in
fontsize: 12pt
linestretch: 2
fig.cap: true
header-includes:
  - \usepackage{float}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Title here: -->
# \textit{Alzheimer's Disease and Aging: Aims 1 and 2}

<!-- Name here: -->
Ezra Weible[^1]

[^1]: Biostatistics Masters Student, Colorado School of Public Health, CU Anschutz Medical Campus

Aim 1 will evaluate whether peripheral inflammatory markers are associated with a 1 year decline in memory and cortical thickness in aMCI. The outcomes will be AD-signature cortical thickness (continuous) and five episodic memory outcomes (continuous; (1) 20' Delay, Total Correct, (2) Recognition, D-Prime, (3) 15' Delay, Total Correct, (4) Proportion Correct, (5) 1-Week Delay, Total Correct). All outcomes will be modeled as a 1 year change (Year 1 - Baseline), and models will include baseline value adjustments to allowing coefficients to be interpreted as the effect on the 1 year change. Hypothesis 1a will examine baseline cytokine (IL-6, TNF-$\alpha$) and chemokine (MCP-1, Eotaxin-1) levels as primary predictors; hypothesis 1b will test changes in these markers over the 1 year period. Each inflammatory marker will be analyzed in separate models to avoid multicollinearity, with exploratory joint models. The general model form for aim 1 will be $Outcome_{Y1-Y0} = \beta_0 + \beta_1 Marker_{Y1 \text{ or } Y1-Y0} + \beta_2 Outcome_{Y0} + \beta_n Covariates + \epsilon$ with an alternative hypothesis that $\beta_1 \neq 0$. 

Aim 2 will examine whether amyloid deposition modifies the relationship between inflammation and clinical progression. The primary hypothesis will test whether baseline amyloid deposition interacts with baseline inflammatory markers to predict a one year decline in episodic memory and cortical thickness. The secondary hypothesis will test whether baseline amyloid deposition interacts with the 1 year change in inflammatory markers to predict the one year decline in the outcomes. Models will follow a similar approach to aim 1, but will include baseline amyloid and an interaction. The general model form for aim 2 will be $Outcome_{Y1-Y0} = \beta_0 + \beta_1 Marker_{Y1 \text{ or } Y1-Y0} + \beta_2 Amyloid_{Y0} + \beta_3 Marker_{Y1 \text{ or } Y1-Y0} * Amyloid_{Y0} + \beta_4 Outcome_{Y0} + \beta_n Covariates + \epsilon$ with an alternative hypothesis that $\beta_3 \neq 0$. 

All models will adjust for age, sex, APOE status, and baseline outcome *a priori*. Additional potential covariates (including education, baseline CDR, GDS,BMI, hypercholesterolemia, blood pressure, NSAID use, immune-related health conditions, and cardiovascular risk) will be evaluated as potential confounders or precision variables. This evaluation will rely on simple exploratory checks of association among markers, outcomes, and candidate covariates. Variables that primarily improve precision will be added to the final models, improving power. Interpretation will be cautious in the presence of correlated variables. Given correlations among outcomes and markers, a mild multiple-comparison approach will be implemented. Once empirical correlations are known, more formal adjustments will be explored. For primary analyses, type I error will be controlled with an adjusted Bonferroni approach by dividing $\alpha$ by 4 (markers), 6 (outcomes), and 24 (markers*outcomes), applied separately within each hypothesis.

For power, each hypothesis will be approximated using a linear regression framework with a continuous predictor (inflammatory marker or amyloid*marker interaction). Because all longitudinal analyses model year 1 outcomes adjusted for baseline values, we can express the effect of interest as the partial $R^2$ attributable to the predictor of interest. This can be approximated as the squared correlation coefficient (with the effective sample size adjusted for baseline correlation with the year 1 outcome). Power analysis can then be conducted to determine the observable effect size at various power levels with the expected sample size (125 aMCI/50 HC after attrition). This approach will provide a conservative estimate of power, as additional covariates such as age and sex will function as precision variables in the final analysis. Separate power calculations will be performed for each hypothesis. 

\newpage
## Appendix 

Code Directory: https://github.com/eweible/BIOS6624.git

File name: P2/Code/P2_Data_Analysis_Plan.Rmd